name: Check build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Rebuild the dist/ directory
        run: yarn build
